replicaCount: 2

image:
  repository: ghcr.io/kazimc4n/insider_case
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi