apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insider-case.fullname" . }}
  labels:
    {{- include "insider-case.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "insider-case.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insider-case.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: GIT_SHA
              value: {{ .Values.env.GIT_SHA | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}